import type { Match, MatchFeed } from "@/types/match";

const DEMO_MATCHES: Match[] = [
  {
    id: 101,
    league: "Premier League",
    country: "England",
    venue: "Emirates Stadium",
    kickoffISO: "2026-02-23T19:45:00Z",
    status: "LIVE",
    minute: 63,
    home: { name: "Arsenal", short: "ARS", form: { recent: "WWDWW", goalsFor: 12, goalsAgainst: 4 } },
    away: { name: "Brighton", short: "BHA", form: { recent: "LDWLW", goalsFor: 8, goalsAgainst: 7 } },
    score: { home: 2, away: 1 },
    odds: { home: 1.74, draw: 3.8, away: 4.6, over25: 1.62, btts: 1.71 },
    marketHistory: [
      { label: "Open", home: 1.86, draw: 3.65, away: 4.4 },
      { label: "6h", home: 1.82, draw: 3.72, away: 4.5 },
      { label: "1h", home: 1.78, draw: 3.77, away: 4.55 },
      { label: "Now", home: 1.74, draw: 3.8, away: 4.6 },
    ],
    bookmakerOdds: [
      { bookmaker: "Betway", home: 1.74, draw: 3.8, away: 4.6 },
      { bookmaker: "Pinnacle", home: 1.78, draw: 3.72, away: 4.5 },
      { bookmaker: "1xBet", home: 1.76, draw: 3.78, away: 4.55 },
    ],
    prediction: { confidence: 76, advice: "Home Win", expectedGoals: 2.9 },
    events: [
      { minute: 14, team: "Arsenal", type: "Goal", player: "Saka", detail: "Left-footed finish" },
      { minute: 38, team: "Brighton", type: "Goal", player: "Ferguson", detail: "Header from corner" },
      { minute: 45, team: "Brighton", type: "Card", player: "Gross", detail: "Yellow Card" },
      { minute: 59, team: "Arsenal", type: "Goal", player: "Martinelli", detail: "Counter attack" },
    ],
    stats: {
      possession: { home: 58, away: 42 },
      shots: { home: 9, away: 5 },
      shotsOnTarget: { home: 5, away: 3 },
      xg: { home: 2.1, away: 0.8 },
      passAccuracy: { home: 87, away: 79 },
      corners: { home: 5, away: 2 },
    },
  },
  {
    id: 102,
    league: "La Liga",
    country: "Spain",
    venue: "Mestalla",
    kickoffISO: "2026-02-23T20:00:00Z",
    status: "UPCOMING",
    home: { name: "Valencia", short: "VAL", form: { recent: "DWLWD", goalsFor: 6, goalsAgainst: 6 } },
    away: { name: "Sevilla", short: "SEV", form: { recent: "WDDWL", goalsFor: 7, goalsAgainst: 5 } },
    score: { home: 0, away: 0 },
    odds: { home: 2.32, draw: 3.1, away: 3.0, over25: 1.95, btts: 1.82 },
    marketHistory: [
      { label: "Open", home: 2.45, draw: 3.05, away: 2.9 },
      { label: "6h", home: 2.4, draw: 3.08, away: 2.92 },
      { label: "1h", home: 2.35, draw: 3.1, away: 2.96 },
      { label: "Now", home: 2.32, draw: 3.1, away: 3.0 },
    ],
    bookmakerOdds: [
      { bookmaker: "Betway", home: 2.32, draw: 3.1, away: 3.0 },
      { bookmaker: "Pinnacle", home: 2.36, draw: 3.06, away: 2.95 },
      { bookmaker: "1xBet", home: 2.34, draw: 3.08, away: 2.98 },
    ],
    prediction: { confidence: 64, advice: "Under 2.5", expectedGoals: 2.1 },
    events: [],
  },
  {
    id: 103,
    league: "Serie A",
    country: "Italy",
    venue: "Stadio Olimpico",
    kickoffISO: "2026-02-23T17:30:00Z",
    status: "FINISHED",
    home: { name: "Roma", short: "ROM", form: { recent: "WDLWW", goalsFor: 9, goalsAgainst: 6 } },
    away: { name: "Torino", short: "TOR", form: { recent: "DLWDW", goalsFor: 6, goalsAgainst: 6 } },
    score: { home: 1, away: 1 },
    odds: { home: 1.92, draw: 3.35, away: 4.2, over25: 1.88, btts: 1.74 },
    marketHistory: [
      { label: "Open", home: 2.02, draw: 3.3, away: 4.0 },
      { label: "6h", home: 1.98, draw: 3.32, away: 4.05 },
      { label: "1h", home: 1.95, draw: 3.33, away: 4.12 },
      { label: "Close", home: 1.92, draw: 3.35, away: 4.2 },
    ],
    bookmakerOdds: [
      { bookmaker: "Betway", home: 1.92, draw: 3.35, away: 4.2 },
      { bookmaker: "Pinnacle", home: 1.96, draw: 3.3, away: 4.1 },
      { bookmaker: "1xBet", home: 1.94, draw: 3.33, away: 4.16 },
    ],
    prediction: { confidence: 58, advice: "BTTS Yes", expectedGoals: 2.3 },
    events: [
      { minute: 22, team: "Roma", type: "Goal", player: "Dybala", detail: "Penalty" },
      { minute: 34, team: "Roma", type: "Card", player: "Smalling", detail: "Yellow Card" },
      { minute: 65, team: "Torino", type: "Substitution", player: "Lukic", detail: "Replaces Ricci" },
      { minute: 71, team: "Torino", type: "Goal", player: "Sanabria", detail: "Close range finish" },
      { minute: 78, team: "Roma", type: "Substitution", player: "Abraham", detail: "Replaces Dybala" },
      { minute: 88, team: "Torino", type: "Card", player: "Buongiorno", detail: "Yellow Card" },
    ],
    stats: {
      possession: { home: 54, away: 46 },
      shots: { home: 11, away: 8 },
      shotsOnTarget: { home: 4, away: 3 },
      xg: { home: 1.4, away: 1.1 },
      passAccuracy: { home: 85, away: 81 },
      corners: { home: 6, away: 4 },
    },
  },
  {
    id: 104,
    league: "Bundesliga",
    country: "Germany",
    venue: "BayArena",
    kickoffISO: "2026-02-23T18:00:00Z",
    status: "LIVE",
    minute: 28,
    home: { name: "Leverkusen", short: "B04", form: { recent: "WWWWW", goalsFor: 15, goalsAgainst: 3 } },
    away: { name: "Mainz", short: "M05", form: { recent: "LDLWW", goalsFor: 7, goalsAgainst: 8 } },
    score: { home: 1, away: 0 },
    odds: { home: 1.52, draw: 4.2, away: 6.4, over25: 1.55, btts: 1.85 },
    marketHistory: [
      { label: "Open", home: 1.62, draw: 4.0, away: 5.9 },
      { label: "6h", home: 1.58, draw: 4.1, away: 6.1 },
      { label: "1h", home: 1.55, draw: 4.15, away: 6.25 },
      { label: "Now", home: 1.52, draw: 4.2, away: 6.4 },
    ],
    bookmakerOdds: [
      { bookmaker: "Betway", home: 1.52, draw: 4.2, away: 6.4 },
      { bookmaker: "Pinnacle", home: 1.56, draw: 4.05, away: 6.1 },
      { bookmaker: "1xBet", home: 1.54, draw: 4.14, away: 6.3 },
    ],
    prediction: { confidence: 81, advice: "Home Win & Over 1.5", expectedGoals: 3.1 },
    events: [
      { minute: 19, team: "Leverkusen", type: "Goal", player: "Wirtz", detail: "Curling shot" },
      { minute: 23, team: "Mainz", type: "Card", player: "Kohr", detail: "Yellow Card" },
    ],
    stats: {
      possession: { home: 62, away: 38 },
      shots: { home: 6, away: 2 },
      shotsOnTarget: { home: 3, away: 1 },
      xg: { home: 1.2, away: 0.3 },
      passAccuracy: { home: 89, away: 74 },
      corners: { home: 4, away: 1 },
    },
  },
  {
    id: 105,
    league: "Ligue 1",
    country: "France",
    venue: "Groupama Stadium",
    kickoffISO: "2026-02-23T21:00:00Z",
    status: "UPCOMING",
    home: { name: "Lyon", short: "OL", form: { recent: "WDLWL", goalsFor: 8, goalsAgainst: 8 } },
    away: { name: "Nice", short: "OGCN", form: { recent: "WDWWW", goalsFor: 10, goalsAgainst: 4 } },
    score: { home: 0, away: 0 },
    odds: { home: 2.65, draw: 3.2, away: 2.7, over25: 2.05, btts: 1.79 },
    marketHistory: [
      { label: "Open", home: 2.58, draw: 3.18, away: 2.8 },
      { label: "6h", home: 2.61, draw: 3.19, away: 2.75 },
      { label: "1h", home: 2.63, draw: 3.2, away: 2.72 },
      { label: "Now", home: 2.65, draw: 3.2, away: 2.7 },
    ],
    bookmakerOdds: [
      { bookmaker: "Betway", home: 2.65, draw: 3.2, away: 2.7 },
      { bookmaker: "Pinnacle", home: 2.61, draw: 3.22, away: 2.74 },
      { bookmaker: "1xBet", home: 2.63, draw: 3.2, away: 2.72 },
    ],
    prediction: { confidence: 61, advice: "Draw No Bet: Nice", expectedGoals: 2.4 },
    events: [],
  },
];

export function getDemoMatchFeed(): MatchFeed {
  return {
    source: "demo",
    updatedAtISO: new Date().toISOString(),
    matches: DEMO_MATCHES,
  };
}
